import { ProductInfo, Recipe } from "@/types";

export const MOCK_PRODUCTS: ProductInfo[] = [
  {
    ean_code: "8594013425054",
    product_name: "Chléb celozrnný",
    brand: "Penam",
    category: "Pekárenské výrobky",
    subcategory: "Chleby",
    image_url: "",
    weight_g: 500,
    unit: "g",
    calories_kcal: 245,
    protein_g: 8.5,
    fat_g: 1.8,
    saturated_fat_g: 0.3,
    carbs_g: 48,
    sugar_g: 3.2,
    fiber_g: 6.5,
    salt_g: 1.1,
    allergens: ["gluten"],
    typical_expiry_days: 5,
    source: "user_added",
    verified: true,
  },
  {
    ean_code: "8000500037560",
    product_name: "Eidam 30%",
    brand: "Madeta",
    category: "Mléčné výrobky",
    subcategory: "Sýry",
    image_url: "",
    weight_g: 100,
    unit: "g",
    calories_kcal: 260,
    protein_g: 25,
    fat_g: 17,
    saturated_fat_g: 11,
    carbs_g: 0.5,
    sugar_g: 0.5,
    fiber_g: 0,
    salt_g: 1.8,
    allergens: ["milk"],
    typical_expiry_days: 21,
    source: "user_added",
    verified: true,
  },
  {
    ean_code: "4003015010015",
    product_name: "Hovězí přední bez kosti",
    brand: "Váhala",
    category: "Maso",
    subcategory: "Hovězí",
    image_url: "",
    weight_g: 350,
    unit: "g",
    calories_kcal: 143,
    protein_g: 21,
    fat_g: 6.5,
    saturated_fat_g: 2.8,
    carbs_g: 0,
    sugar_g: 0,
    fiber_g: 0,
    salt_g: 0.1,
    allergens: [],
    typical_expiry_days: 4,
    source: "user_added",
    verified: true,
  },
];

export const MOCK_RECIPES: Recipe[] = [
  {
    id: "gulas",
    name: "Hovězí guláš",
    description: "Tradiční český hovězí guláš s cibulí a paprikou",
    image_url: "",
    servings: 4,
    prep_time_min: 20,
    cook_time_min: 120,
    calories_per_serving: 680,
    protein_per_serving: 52,
    fat_per_serving: 28,
    carbs_per_serving: 45,
    ingredients: [
      { name: "Hovězí přední", quantity: 500, unit: "g", ean_code: "4003015010015" },
      { name: "Cibule", quantity: 3, unit: "ks" },
      { name: "Paprika červená", quantity: 2, unit: "ks" },
      { name: "Kmín", quantity: 5, unit: "g" },
      { name: "Sladká paprika", quantity: 10, unit: "g" },
      { name: "Sůl", quantity: 5, unit: "g" },
      { name: "Olej", quantity: 30, unit: "ml" },
    ],
    instructions: [
      "Nakrájejte maso na kostky cca 3×3 cm.",
      "Orestujte nakrájenou cibuli na oleji do zlatova.",
      "Přidejte maso a opečte ze všech stran.",
      "Vmíchejte papriku sladkou, kmín a osolte.",
      "Zalijte vodou, přikryjte a duste 90 minut.",
      "Přidejte nakrájenou papriku a duste dalších 20 minut.",
      "Dochuťte, podávejte s houskovým knedlíkem.",
    ],
    tags: ["hovězí", "klasika", "česká kuchyně", "nedělní oběd"],
  },
  {
    id: "kuřecí-stir-fry",
    name: "Kuřecí stir-fry",
    description: "Rychlé kuřecí s barevnou zeleninou",
    image_url: "",
    servings: 2,
    prep_time_min: 10,
    cook_time_min: 15,
    calories_per_serving: 420,
    protein_per_serving: 45,
    fat_per_serving: 12,
    carbs_per_serving: 30,
    ingredients: [
      { name: "Kuřecí prsa", quantity: 400, unit: "g" },
      { name: "Paprika", quantity: 2, unit: "ks" },
      { name: "Cibule", quantity: 1, unit: "ks" },
      { name: "Sojová omáčka", quantity: 30, unit: "ml" },
      { name: "Česnek", quantity: 2, unit: "stroužky" },
      { name: "Zázvor", quantity: 5, unit: "g" },
    ],
    instructions: [
      "Nakrájejte kuřecí maso na proužky.",
      "Rozpalte wok nebo pánev na vysokou teplotu.",
      "Opečte maso 3–4 minuty, odložte.",
      "Orestujte zeleninu 2–3 minuty.",
      "Vraťte maso, přidejte sojovou omáčku.",
      "Promíchejte a ihned podávejte s rýží.",
    ],
    tags: ["kuřecí", "rychlé", "zdravé", "asijské"],
  },
  {
    id: "brokolicova-polevka",
    name: "Krémová brokolicová polévka",
    description: "Lahodná smetanová polévka z brokolice",
    image_url: "",
    servings: 3,
    prep_time_min: 10,
    cook_time_min: 25,
    calories_per_serving: 280,
    protein_per_serving: 12,
    fat_per_serving: 18,
    carbs_per_serving: 20,
    ingredients: [
      { name: "Brokolice", quantity: 500, unit: "g" },
      { name: "Cibule", quantity: 1, unit: "ks" },
      { name: "Česnek", quantity: 2, unit: "stroužky" },
      { name: "Smetana ke vaření", quantity: 200, unit: "ml" },
      { name: "Zeleninový vývar", quantity: 500, unit: "ml" },
    ],
    instructions: [
      "Nakrájejte cibuli a česnek, orestujte na másle.",
      "Přidejte brokolici a vývar, vařte 15 minut.",
      "Rozmixujte tyčovým mixérem do hladka.",
      "Vmíchejte smetanu, dochuťte, servírujte.",
    ],
    tags: ["vegetariánské", "polévka", "rychlé"],
  },
];
